import { useState } from "react";
import { submitFeedback } from "../services/api";

const CATEGORIES = [
  { value: "general", label: "General" },
  { value: "bug", label: "Bug Report" },
  { value: "feature", label: "Feature Request" },
];

const FAQ = [
  {
    q: "Does SproutRoute work for international destinations?",
    a: "Currently, weather forecasts are limited to US locations (via weather.gov). You can still enter international destinations for itinerary and packing suggestions, but weather data won't be available.",
  },
  {
    q: "Is SproutRoute free to use?",
    a: "Yes! SproutRoute is completely free. We may introduce optional premium features in the future, but the core trip planning and packing list functionality will always remain free.",
  },
  {
    q: "How accurate are the packing lists?",
    a: "Packing lists are generated by AI based on your destination, weather, dates, and children's ages. They're a great starting point, but we recommend reviewing and adjusting based on your family's specific needs.",
  },
  {
    q: "Can I save or share my trip plan?",
    a: "Trip data is automatically saved in your browser. You can also print your packing checklist. Sharing and export features are on our roadmap.",
  },
  {
    q: "My trip plan seems inaccurate. What should I do?",
    a: 'AI-generated plans may occasionally contain outdated or incorrect information. Use the "Customize" button to adjust activities, and always verify venue details independently. If something looks wrong, let us know through the form below.',
  },
];

export default function SupportPage() {
  const [category, setCategory] = useState("general");
  const [message, setMessage] = useState("");
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState("idle");
  const [errorMsg, setErrorMsg] = useState("");
  const [openFaq, setOpenFaq] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (message.trim().length < 5) {
      setErrorMsg("Please write at least 5 characters.");
      return;
    }

    setStatus("sending");
    setErrorMsg("");

    try {
      await submitFeedback({
        category,
        message: message.trim(),
        email: email.trim(),
      });
      setStatus("success");
      setMessage("");
      setEmail("");
      setCategory("general");
    } catch (err) {
      setStatus("error");
      setErrorMsg(err.message || "Something went wrong.");
    }
  };

  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <p className="text-xs uppercase tracking-[0.3em] text-muted">Support</p>
      <h1 className="mt-2 text-3xl md:text-4xl font-semibold text-paper">
        How can we help?
      </h1>
      <p className="mt-2 text-sm text-muted">
        Check the FAQ below or send us a message. We read every submission.
      </p>

      {/* FAQ */}
      <div className="mt-12">
        <h2 className="text-xl font-semibold text-paper mb-4">
          Frequently Asked Questions
        </h2>
        <div className="space-y-2">
          {FAQ.map((item, i) => (
            <div
              key={i}
              className="rounded-2xl border border-white/10 bg-white/5 overflow-hidden"
            >
              <button
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full flex items-center justify-between px-5 py-4 text-left text-sm font-medium text-paper hover:text-primary-500 transition"
              >
                <span>{item.q}</span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className={`shrink-0 ml-4 text-muted transition-transform ${
                    openFaq === i ? "rotate-180" : ""
                  }`}
                >
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              {openFaq === i && (
                <div className="px-5 pb-4 text-sm text-muted leading-relaxed">
                  {item.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Contact Form */}
      <div className="mt-16">
        <h2 className="text-xl font-semibold text-paper mb-4">
          Send us a message
        </h2>

        {status === "success" ? (
          <div className="rounded-2xl border border-primary-500/30 bg-primary-500/5 p-8 text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-primary-500/20 text-primary-500 mb-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="28"
                height="28"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </div>
            <p className="text-lg font-semibold text-paper">Message sent!</p>
            <p className="mt-1 text-sm text-muted">
              Thank you for reaching out. We'll get back to you if you provided
              an email.
            </p>
            <button
              onClick={() => setStatus("idle")}
              className="mt-4 rounded-full border border-white/20 px-6 py-2 text-xs uppercase tracking-[0.2em] text-paper hover:border-primary-500 transition"
            >
              Send another message
            </button>
          </div>
        ) : (
          <form
            onSubmit={handleSubmit}
            className="space-y-5 rounded-2xl border border-white/10 bg-white/5 p-6"
          >
            {errorMsg && (
              <div className="rounded-2xl border border-red-500/40 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                {errorMsg}
              </div>
            )}

            {/* Category */}
            <div>
              <label className="text-xs uppercase tracking-[0.2em] text-muted block mb-2">
                Category
              </label>
              <div className="flex gap-2">
                {CATEGORIES.map((cat) => (
                  <button
                    key={cat.value}
                    type="button"
                    onClick={() => setCategory(cat.value)}
                    className={`rounded-full border px-4 py-1.5 text-xs uppercase tracking-[0.15em] transition ${
                      category === cat.value
                        ? "border-primary-500 bg-primary-500/20 text-primary-500"
                        : "border-white/10 text-muted hover:border-white/30"
                    }`}
                  >
                    {cat.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Message */}
            <div>
              <label className="text-xs uppercase tracking-[0.2em] text-muted block mb-2">
                Message
              </label>
              <textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="Tell us what's on your mind..."
                rows={5}
                maxLength={2000}
                className="w-full resize-none rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-paper placeholder:text-muted focus:border-primary-500 focus:outline-none"
              />
            </div>

            {/* Email */}
            <div>
              <label className="text-xs uppercase tracking-[0.2em] text-muted block mb-2">
                Email (optional)
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com — so we can follow up"
                className="w-full border-b border-white/20 bg-transparent py-3 text-sm text-paper placeholder:text-muted focus:border-primary-500 focus:outline-none"
              />
            </div>

            <button
              type="submit"
              disabled={status === "sending"}
              className="rounded-full bg-primary-500 px-6 py-3 text-sm font-semibold text-ink transition hover:bg-primary-600 disabled:opacity-60"
            >
              {status === "sending" ? "Sending..." : "Send Message"}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
