export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <p className="text-xs uppercase tracking-[0.3em] text-muted">Legal</p>
      <h1 className="mt-2 text-3xl md:text-4xl font-semibold text-paper">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted">
        Last updated: February 24, 2026
      </p>

      <div className="mt-10 space-y-8 text-sm text-muted leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using SproutRoute (www.sproutroute.app), you agree
            to be bound by these Terms of Service. If you do not agree to these
            terms, please do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            2. Description of Service
          </h2>
          <p>
            SproutRoute is an AI-powered trip planning tool that helps parents
            plan family-friendly trips. The service provides weather forecasts,
            suggested itineraries, and packing checklists based on user-provided
            trip details. The service is provided "as is" and is intended for
            informational and planning purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            3. Use of the Service
          </h2>
          <p className="mb-3">You agree to use SproutRoute only for its intended purpose. You may not:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>
              Use automated systems (bots, scrapers) to access the service
            </li>
            <li>Attempt to overload, disrupt, or interfere with the service</li>
            <li>
              Use the service for any unlawful purpose
            </li>
            <li>
              Submit harmful, abusive, or offensive content through feedback or
              any input fields
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            4. AI-Generated Content
          </h2>
          <p>
            Trip itineraries, packing lists, and activity suggestions are
            generated by artificial intelligence (Anthropic's Claude). While we
            strive for accuracy, AI-generated content may contain errors,
            omissions, or outdated information. You should independently verify
            any critical information — especially regarding safety, travel
            advisories, venue hours, and medical or allergy-related packing
            needs.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            5. Weather Data
          </h2>
          <p>
            Weather forecasts are sourced from the National Weather Service
            (weather.gov) and are limited to US locations. Forecasts are
            inherently uncertain and should not be relied upon as the sole basis
            for safety-critical decisions. Always check official sources before
            traveling during severe weather.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            6. Rate Limiting
          </h2>
          <p>
            To ensure fair access for all users, SproutRoute enforces rate
            limits on API requests. Exceeding these limits will result in
            temporary throttling. Continued abuse may result in permanent
            access restrictions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            7. Intellectual Property
          </h2>
          <p>
            The SproutRoute name, logo, and website design are the property of
            SproutRoute. Trip plans and packing lists generated for you are
            yours to use freely. You may not reproduce, distribute, or create
            derivative works from the SproutRoute platform itself.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            8. Limitation of Liability
          </h2>
          <p>
            SproutRoute is provided on an "as is" and "as available" basis. We
            make no warranties, expressed or implied, regarding the accuracy,
            reliability, or availability of the service. In no event shall
            SproutRoute or its creators be liable for any indirect, incidental,
            special, or consequential damages arising from your use of the
            service, including but not limited to lost items, missed
            activities, or travel disruptions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            9. Modifications
          </h2>
          <p>
            We reserve the right to modify or discontinue the service at any
            time, with or without notice. We may also update these Terms of
            Service from time to time. Continued use of the service after
            changes constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-paper mb-2">
            10. Contact
          </h2>
          <p>
            If you have questions about these Terms of Service, please contact
            us through our{" "}
            <a
              href="/support"
              className="text-primary-500 hover:underline"
            >
              Support page
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
